### PR TITLE
Dynamic steering

### PR DESCRIPTION
**Pull request by njm222**
the slower the car is moving the greater the turning radius

### CODE REVIEW

**Comment by drcmda** [comment]
could you resolve? i cleaned up the chassis model. will it still drift in a similar way when its fast?

**Comment by njm222** [comment]
So it will drift in a similar way, not exactly as before. 
When going _very_ fast the `dynamicSteer`is < 0.3 (0.3 was the old static steer). We can just add a clamp to keep the drift the same.

**Comment by drcmda** [comment]
i think this needs some more work, i think it behaves a little awkward when going fast.

**Comment by njm222** [comment]
If we clamp the dynamicSteer, it should behave like the old version when going fast but still maintain the greater turning radius when going slow. I can do this shortly.

**Pull request merged**
