### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by njm222**
Added issue templates

### CODE REVIEW

**Comment by Gusted** [comment]
I think a little warning something along the lines of
```markdown

<!-- 
  ⚠⚠ Do not delete this issue template! ⚠⚠ 
  Issues that do not use the issue template/don't fill out the essential information are likely to be ignored and closed. 
-->
```
could be added so you don't have to go back and forth on people to just get basic information about the problem. And hopefully prevent issues with a single sentence.

**Comment by drcmda** [comment]
is this ready to go? github ci is bugged today it seems or is that something actually breaking?

**Comment by Gusted** [comment]
>  it seems or is that something actually breaking?

Prettier :)

```diff
--- a/.github/ISSUE_TEMPLATE/bug_report.md
+++ b/.github/ISSUE_TEMPLATE/bug_report.md
@@ -4,7 +4,6 @@ about: Create a report to help us improve
 title: ''
 labels: ''
 assignees: ''
-
 ---
 
 **Describe the bug**
@@ -12,6 +11,7 @@ A clear and concise description of what the bug is.
 
 **To Reproduce**
 Steps to reproduce the behavior:
+
 1. Go to '...'
 2. Click on '....'
 3. Scroll down to '....'
@@ -24,15 +24,17 @@ A clear and concise description of what you expected to happen.
 If applicable, add screenshots to help explain your problem.
 
 **Desktop (please complete the following information):**
- - OS: [e.g. iOS]
- - Browser [e.g. chrome, safari]
- - Version [e.g. 22]
+
+- OS: [e.g. iOS]
+- Browser [e.g. chrome, safari]
+- Version [e.g. 22]
 
 **Smartphone (please complete the following information):**
- - Device: [e.g. iPhone6]
- - OS: [e.g. iOS8.1]
- - Browser [e.g. stock browser, safari]
- - Version [e.g. 22]
+
+- Device: [e.g. iPhone6]
+- OS: [e.g. iOS8.1]
+- Browser [e.g. stock browser, safari]
+- Version [e.g. 22]
 
 **Additional context**
 Add any other context about the problem here.
diff --git a/.github/ISSUE_TEMPLATE/feature_request.md b/.github/ISSUE_TEMPLATE/feature_request.md
index bbcbbe7..2f28cea 100644
--- a/.github/ISSUE_TEMPLATE/feature_request.md
+++ b/.github/ISSUE_TEMPLATE/feature_request.md
@@ -4,7 +4,6 @@ about: Suggest an idea for this project
 title: ''
 labels: ''
 assignees: ''
-
 ---
 
 **Is your feature request related to a problem? Please describe.**
```

**Comment by drcmda** [comment]
CI is my weakness, but i dont understand why it's doing this 😅 it should auto transform every staged file, not run run a check. maybe @gsimone or @dbismut can help with this, they set up a lot of projects on here.

**Comment by Gusted** [comment]
> CI is my weakness, i dont understand why it's doing this sweat_smile it should auto transform every staged file

Yeah it should. I'm not sure about @njm222 workflows but it might be using some external GIT GUI(ex. gitkraken) which doesn't support's husky's v5+ behavior about hooks and therefore ignores the hooks. Il send some PR to fix this behavior.

**Comment by njm222** [comment]
Yeah I did this on github, which probably didn't trigger the pre-check

**Pull request merged**
