### PR TITLE
Add better boost

### PR DESCRIPTION
**Pull request by dj24**
Adds a boost effect, a bit of screen shake, and a sound effect when boosting. Would be nice to get a boost bar in below the speed bar

download

### CODE REVIEW

**Comment by drcmda** [comment]
this is awesome 😅 could you pls fix the conflicts then lets merge it

**Comment by drcmda** [comment]
it sounds a bit like a fart though 😅

**Comment by dj24** [comment]
> it sounds a bit like a fart though 😅

😂😂 ill get a better sound in

**Comment by dj24** [comment]
conflicts fixed

**Pull request merged**
