### PR TITLE
Run prettier fix

### PR DESCRIPTION
**Pull request by Gusted**
This should fix the CI errors.

### CODE REVIEW

**Comment by drcmda** [comment]
i think it's still broken @Gusted do you know what causes it? https://github.com/pmndrs/racing-game/runs/2755044136?check_suite_focus=true

**Comment by Gusted** [comment]
> @Gusted do you know what causes it?

You forgot to add parentheses

```diff
-  const chassisBody = useStore(state => state.raycast.chassisBody)
-  const map = useStore(state => state.controls.map)
+  const chassisBody = useStore((state) => state.raycast.chassisBody)
+  const map = useStore((state) => state.controls.map)
```



> i think it's still broken

It isn't. Maybe run `yarn run prettier-fix` before committing the code 😄. Or like I do it: Get notifications github actions failed. Knows right away to run the command and push another commit.

**Comment by drcmda** [comment]
but thats the thing, the action crashes without giving a reason

**Comment by Gusted** [comment]
> but thats the thing, the action crashes without giving a reason

At the moment it list the files where there is a difference. I'm not sure if prettier has the ability to show the the exact diff. 

But it should just error out as at this moment PR x could implement a change and didn't prettied and if I open another pr based off that commit it will prettied that file which could be totally unrelated to that PR.

**Pull request merged**
