### PR TITLE
Feat/minimap

### PR DESCRIPTION
**Pull request by ekaradon**
First proposal for a mini map.

Screenshot_20210602_225204

It will need more work because for now there is a bit of a visibility issue. So we can consider this like a starting point for this feature?

### CODE REVIEW

**Comment by drcmda** [comment]
i think i'd prefer a simpler head up display with a plane and a texture + location.

the problem otherwise would be the overhead and performance hit, it would essentially double render the entire scene.

**Comment by ekaradon** [comment]
Okay, do you think it would be possible to generate the texture from the scene? So we won't have to think about it if we want to modify the level or change it entirely?

**Comment by drcmda** [comment]
Well you could render it into a texture once with a orthographic camera looking from above.

**Comment by ekaradon** [comment]
Okay, I'm going to rewrite all this. Will update this pull request once it's done.

**Comment by ekaradon** [comment]
Hello,
So I've make some progress, and now I have a mini map which follow my camera.
Peek 03-06-2021 20-35
But I think I will need another approach because it becomes really difficult to position the mini map right. 
Especially with the different camera options (bird, FPS, TPS). 
So what I suggest is to have another render with an orthographic camera on an empty scene containing just a sprite with the texture generated. 
You can see something related here: https://threejs.org/examples/webgl_sprites.html
I don't think it would cost that much to use this method.

**Comment by MANTENN** [comment]
> Hello,
> So I've make some progress, and now I have a mini map which follow my camera.
> Peek 03-06-2021 20-35
> But I think I will need another approach because it becomes really difficult to position the mini map right.
> Especially with the different camera options (bird, FPS, TPS).
> So what I suggest is to have another render with an orthographic camera on an empty scene containing just a sprite with the texture generated.
> You can see something related here: https://threejs.org/examples/webgl_sprites.html
> I don't think it would cost that much to use this method.

Would an another canvas solve this problem? The state is not tied to the webgl context

**Comment by drcmda** [comment]
a second canvas woulda second canvas would add some overhead. i think putting a map somewhere as a second render shouldn't be a problem, see: https://codesandbox.io/s/viewcube-py4db

**Comment by ekaradon** [comment]
Hello,

Still working on it but now it's already much better. 
Peek 05-06-2021 12-04
I still need to:

- Add a frame around the map
- Show the player position and update it 
- Handle layers so I avoid to render things that should not show up (car, birds, clouds, ...)
- Fix the map disappearing when hot-reloading the application

However, for now, I've an issue with the texture part. I've added a reference to the level so I can now exactly were exactly are the limits of the level but for a reason I don't understand, the render is not showing the upper part of the level.
I'm still trying to figure out why. Maybe the ratio? But the level has pretty much the same dimensions in the z and x axis, so I'm not sure. Still investigating.

**Comment by ekaradon** [comment]
Just answering to myself, I found the reason why. I was dividing by two the height and width and it could work theoretically but here the level has some of its coordinates under zero, so dividing won't work. Instead I'm just subtracting the center of the level. 

```
    camera.current.bottom = levelBox.min.z - levelCenter.z
    camera.current.top = levelBox.max.z - levelCenter.z
    camera.current.left = levelBox.min.x - levelCenter.x
    camera.current.right = levelBox.max.x - levelCenter.x
```

**Comment by ekaradon** [comment]
Yeaah, I finally got it working with the player position! :partying_face: 
Peek 05-06-2021 15-04
I'm a bit confused by what I had to do however. For example:

```javascript
    direction.subVectors(chassisBody.current.position, levelCenter)
    const ratioX = size / levelDimensions.x
    const ratioY = levelDimensions.y / size // why here it's the opposite?
    player.current.position.set(screenPosition.x + direction.x * ratioX, screenPosition.y - direction.z * ratioY, 0)
```
If someone can explain that to me, I would be happy to hear it. 

Still working on it, I just push my progress gradually but may rebase everything once I'm done. 
I still have no clue why the mini map disappears after a hot-reload (following a modification of code) but it's related to this line:
```javascript
    // level.current is the ref to the group of ground meshes
    const box = new Box3().setFromObject(level.current)
```
After a hot-reload, box is recomputed and everything is filled of NaN.

**Comment by ekaradon** [comment]
So here is the last feature task I had in mind; the frame:
Screenshot_20210605_183801

So that's it for the features I suppose? I know that probably a lot can be done yet to enhance the mini map but it would probably be best to go step by step. 

And now, there is a lot of bugs to fix :sweat_smile:  
 - As previously stated, a hot-reload make the mini map disappears
 - The size of the mini map is a parameter of the component, but modifying the size (from 300 to whatever value) is making the player position goes wrong... which probably means I was lucky in my first try?
 - When the game starts the map is displayed. I wanted to do the opposite but... when the game starts with the mini map hidden and we then display it, it's displayed without the directional light and so it looks a bit ugly. I don't understand why because the frame buffer object is processed at the start of the game independently of the mini map displayed. 

I'm going to rebase the pull request now so someone can already review it.

**Comment by drcmda** [comment]
Hey good work! Don't forget to pull master into the pr to fix the nerve conflicts. Can't wait for the minimap 😃

**Comment by ekaradon** [comment]
@drcmda : it's done. However, the map is now a bit broken because of the bomb model addition into the level (I thought the bomb was a bug to be honest the first time I saw this):
Screenshot_20210605_222323
So either I'm displaying the bomb in the mini map, either I'm removing the bomb from the bounding box? 

Still three bugs (see the checkbox above)

**Comment by drcmda** [comment]
bomb?

**Comment by ekaradon** [comment]
Yup... I was as surprised as you are. :confused: 

Screenshot_20210605_224316

Those are generating a bomb (at least on my computer) in the Track component:

```javascript
      <mesh geometry={n.track_2.geometry} material={m['Material.001']} {...config} />
      <mesh geometry={n.tube.geometry} material={m['default']} {...config} />
```

**Comment by drcmda** [comment]
it's a tunnel and a basin. im trying to connect the two entrances with a tunnel so the map can be driven through infinitely. and the basin is for when the car is under water, then it looks blue

**Comment by ekaradon** [comment]
Okay, it's fixed. And the hot-reload too in the mean time... even if it required to introduce a slight delay computing the bouding box of the level. I don't know why. :|

**Comment by ekaradon** [comment]
The mini map now shows up even with a bird eye camera. Only one last issue. I've no idea about this one however. If someone can give me a clue I would appreciate. We could however merge the pull request nonetheless, it's annoying only if we want to start the game with the map hidden.

**Comment by drcmda** [comment]
dont worry this is great, i think we can iterate on it some more little by little. let's merge it now and then try some variants.

**Pull request merged**
