### PR TITLE
Add option to toggle statsMeter

### PR DESCRIPTION
**Pull request by Gusted**
This should be useful to check the current FPS and how long it take to render 1 frame. Going to be a life-saver in the long term to improve performance

It's using the JSX element from Drei: https://github.com/pmndrs/drei/tree/master/#stats

How it looks:
image

### CODE REVIEW

**Comment by Gusted** [comment]
@drcmda Is it now a Free-For-All and merge your own PR if you think it's good to go?

**Comment by drcmda** [comment]
could you make it show up on debug only?

**Comment by drcmda** [comment]
we need leva folders to group some options, it's getting a bit much :-D

**Comment by Gusted** [comment]
> we need leva folders to group some options, it's getting a bit much :-D

Got that 😄 



> if you have time could you group them?

Sure thing. Just need to finish this other PR to check if the builds can be switched to something faster.

**Pull request merged**
