### PR TITLE
Cleanup Leaderboard

### PR DESCRIPTION
**Pull request by bjornstar**
- [Store] Created a `reset` method that handles everything needed to reset the game
- [Store] `reset` is no longer a property on `control`
- [utils] Moved everything from `utils` into a single data file.
- [data] Added a default config that can be overridden by environment variables
- [data] Don't create a new client on every request
- [data] Changed method names to reflect the name of the database: `scores`
- [Finished] Tweaked wording: "You belong on our leaderboard!"
- [Leaderboard] Fixed bug where clicking on the button would delete the game state
- [Leaderboard] Fetch scores when opening the leaderboard and no more than once every 3 seconds
- [Vehicle] renamed `ctrl` to `controls`
- [Vehicle] imported only the used methods from `three`
- [Vehicle] use maxSpeed instead of vehicleConfig.maxSpeed
- [Store] Moved `angularVelocity`, `position`, & `rotation` back to the store
- [Store] Don't export wheelInfos

Some issues with the Finished component:
1) Setting your name should also submit your score (you have to click add me twice to get your score submitted now)
2) There's no error handling for the data requests
3) There's no progress indicator for the data requests (if they take too long, people will resubmit and we'll get duplicates)
4) The time seems to continue after you've finished

### CODE REVIEW

**Comment by njm222** [comment]
I prefer the way utils was setup before, but I like the rest of the proposed changes!
(I'm currently working on auth and having those functions separate is much cleaner

**Comment by bjornstar** [comment]
> I prefer the way utils was setup before, but I like the rest of the proposed changes!
> (I'm currently working on auth and having those functions separate is much cleaner

The problem with `utils` is that it becomes a dumping ground because technically everything is a utility function.

**Comment by njm222** [comment]
okay I understand your concern, how about we have a directory just for supabase?

**Comment by bjornstar** [comment]
> okay I understand your concern, how about we have a directory just for supabase?

There's a data file that exports two functions, no need to futureproof it now. When the data API changes the file structure can change to match it.

**Comment by drcmda** [comment]
im happy with the changes so far. as for @njm222 suggestion, maybe we rename the folder called store and put the store in it, constants, mutation and supabase? would you like that @bjornstar ?

**Comment by bjornstar** [comment]
> im happy with the changes so far. as for @njm222 suggestion, maybe we rename the folder called store and put the store in it, constants, mutation and supabase? would you like that @bjornstar ?

The file structure here is not permanent, they can be changed after this PR lands. I tried not to change too much as several of my changes have been reverted recently.

**Pull request merged**
