### PR TITLE
add sounds

### PR DESCRIPTION
**Pull request by hazem3500**
# Sounds
- car engine
- honk _(by pressing `H`)_
- brakes _(while braking)_
- train engine

### CODE REVIEW

**Comment by njm222** [comment]
In the future I would love to have the vehicle sounds more dynamic. (engine & brake)

**Comment by hazem3500** [comment]
Yeah, I thought this would be good for a start.
In the future, we can make the engine and brake volume based on the acceleration and the drift.

**Comment by drcmda** [comment]
that was fast :-D awesome, thanks!

the screeching could be two tier. the state model differs between sliding and breaking. it slides already when you see the dust tail. that should also gives some sound, breaking would intensify it.

the engine is a little annoying, maybe something more realistic with revving and breaking up. good start though, and love the train sound.

**Comment by drcmda** [comment]
also wav seems to be really big, i've quickly compressed them to mp3, but i think it still could be less

**Comment by hazem3500** [comment]
Yup, the sound files were pretty big 😅

**Pull request merged**
